# 서버포트설정
server.port: 8082
---
# DB 설정
spring:
  datasource :
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: dtol0330
  jpa:
    hibernate:
      ddl-auto: create

---
#swagger 설정(3이상 버전시 설정)
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
---
## batch 적용
#spring:
#  batch:
#   initialize-schema:  always
    
---
## 파일 사이즈 늘리기
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB 
---
spring:
  jpa:
    show-sql: true
  mysql:
    console:
      enabled: true 
      
---
spring:
  main:
    allow-bean-definition-overriding: true 
    
    
---
## 카멜케이스 컬럼명 적용
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
## mybatis 설정
#mybatis:
#    type-aliases-package: com.sample.springboothelloSubway.dao
#    configuration:
#        map-underscore-to-camel-case: true
#    mapper-locations: classpath:mapper/*.xml
#    executor-type: BATCH
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*.sql
  executorType: BATCH

---

      




        