# 서버포트설정
server:
  port: 8082

# DB 설정
spring:
  datasource :
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: dtol0330
    

---
#swagger 설정(3이상 버전시 설정)
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
---
spring:
  batch:
    initialize-schema:  always
    
---
spring:
  resources:
    location: C:\Users\hhjeo\DtolStudy\spring-boot-hello\storage\